font:
  normal:
    family: monospace
    style: Regular
  size: 13

# spawn a new instance of Alacritty in the current working directory by pressing Ctrl+Shift+Enter: 
key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance } 
